"""
Django settings for squirrel_wallet project.

Generated by 'django-admin startproject' using Django 1.10.7.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '1it6-k8-w(ujef5m3tzg5azya6u^ae2qf*sz2dd$%xz4es7wh5'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

USE_L10N = False

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.sites',
    'django.contrib.staticfiles',
    'registration',
    'django.contrib.auth',
    'wallet',
    'django_extensions',
    'django_countries',
]

SITE_ID = 1

ACCOUNT_ACTIVATION_DAYS = 7
REGISTRATION_FORM = 'wallet.forms.UserCreationForm'
INCLUDE_REGISTER_URL = True
MIN_BTC_TX = 0.00000547

AUTHENTICATION_BACKENDS = (
    'wallet.backends.EmailOrUUIDModelBackend',
    'django.contrib.auth.backends.ModelBackend'
)
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'squirrelwalletlicom@gmail.com'
EMAIL_HOST_PASSWORD = 'faltoco2018'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

AUTH_USER_MODEL = 'wallet.User'
LOGIN_URL = '/account/login/'
LOGIN_REDIRECT_URL = '/wallet/dashboard/'

DATE_INPUT_FORMATS = ('%m-%d-%Y','%Y-%m-%d')

CELERY_BROKER_URL = 'redis://localhost:6379'
CELERY_RESULT_BACKEND = 'redis://localhost:6379'
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TASK_SERIALIZER = 'json'
CELERY_TIMEZONE = 'America/Caracas'
CELERY_BEAT_SCHEDULE = {
    'update_values': {
        'task': 'wallet.tasks.update_values',
        'schedule': 60.00,
    },
    'update_transactions': {
        'task': 'wallet.tasks.update_transactions',
        'schedule': 60.00,
    },
    'update_balances': {
        'task': 'wallet.tasks.update_balances',
        'schedule': 30.00,
    },
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django_otp.middleware.OTPMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'squirrel_wallet.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['./templates',],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'squirrel_wallet.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

PROJECT_DIR = os.path.abspath(os.path.dirname(__file__))

DATABASES = {
        # 'default': {
        #    'ENGINE': 'django.db.backends.sqlite3',
        #    'NAME': os.path.join(PROJECT_DIR, 'squirrel_wallet.db'),
        #}
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'squirrel_wallet',
        'USER': 'licom',
        'PASSWORD': 'licom2018',
        'HOST': 'localhost',   # Or an IP Address that your DB is hosted on
        'PORT': '3306',
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Caracas'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

STATIC_URL = '/static/'
