# Generated by Django 2.0.3 on 2018-03-31 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_confirmed',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='public_key',
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=None),
        ),
    ]
