# Generated by Django 2.0.3 on 2018-03-27 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='protection',
            name='security',
        ),
        migrations.RemoveField(
            model_name='protection',
            name='user',
        ),
        migrations.DeleteModel(
            name='Protection',
        ),
        migrations.DeleteModel(
            name='Security',
        ),
    ]
