# Generated by Django 2.0.5 on 2018-07-14 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='qrcode',
            field=models.ImageField(blank=True, null=True, upload_to='qrcode', verbose_name='QR Code'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=16, verbose_name='Balance'),
        ),
    ]
