# Generated by Django 2.0.5 on 2018-07-14 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_auto_20180714_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='content/avatar/None/no-img.jpg', upload_to='content/avatar'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='qrcode',
            field=models.ImageField(blank=True, null=True, upload_to='static/qrcode', verbose_name='QR Code'),
        ),
    ]
