# Generated by Django 2.0.5 on 2018-07-15 14:41

from django.db import migrations, models
import wallet.helpers
import wallet.storage


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_auto_20180714_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='static/avatar/None/no-img.jpg', storage=wallet.storage.OverwriteStorage(), upload_to=wallet.helpers.RandomFileName('static/avatar')),
        ),
    ]
